name: Deploy

on:
    push:
        branches:
            - prod

    pull_request:
        branches:
            - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "globant-technical-test"
          heroku_email: "frnncs@gmail.com"
