name: Static Test && Unit Test

on:
    pull_request:
        branches: ["test"]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: "Start containers for testing and install requirements."
              run: |
                docker-compose up -d
                docker-compose exec -it app pip3 install -r requirements-test.txt

            - name: "Staic linting with flake8"
              run: docker-compose exec -it app flake8

            - name: "Test coverage with pytest"
              run: docker-compose exec -it app coverage run -m pytest
