name: Static Test && Unit Test

on:
    pull_request:
        branches: ["test"]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: UnitTest with pytest
              run: |
                docker-compose up -d
                docker-compose exec app pip3 install -r requirements-test.txt
                docker-compose exec app flake8
                docker-compose exec app coverage run -m pytest
