name: Static Test && Unit Test

on:
    pull_request:
        branches: ["test"]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: UnitTest with pytest
              run: |
                docker-compose up -d
                docker-compose exec app pip3 install -r requirements-test.txt

            - name: "Wait for docker to finish installing."
              run: sleep 30

            - name: "Staic linting with flake8"
              run: docker-compose exec app flake8

            - name: "Test coverage with pytest"
              run: docker-compose exec app coverage run -m pytest
