name: Static Test && Unit Test

on:
    pull_request:
        branches: ["test"]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.12.2
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12.2
            - uses: actions/setup-python@v5

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/dev.txt

            - name: Start Redis
              uses: supercharge/redis-github-action@1.7.0
              with:
                redis-version: 7.2.4
                redis-port: 6379
                redis-container-name: redis
                redis-remove-container: true # false by default

            - name: Lint with flake8
              run: |
                  flake8
              env:
                  PYTHONPATH: ${{ github.workspace }}

            - name: Test with pytest and coverage
              run: |
                coverage run -m pytest
              env:
                  PYTHONPATH: ${{ github.workspace }}
